services:
  test_app:
    build: .
    ports:
      - "5000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase?schema=public
    depends_on:
      - db
    command: sh -c "npm i && && npx prisma generate && npx prisma migrate deploy && npm start" # runs migrations then starts the app

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
